input_data = open('input.txt', 'r') 
data = input_data.readlines()
a = str(data[0])
b = str(data[1])
c = str(data[2])
d = str(data[3])
a = a.split()
b = b.split()
c = c.split()
d = d.split()
x1 = int(a[0])
y1 = int(a[1])
x2 = int(b[0])
y2 = int(b[1])
x3 = int(c[0])
y3 = int(c[1])
x4 = int(d[0])
y4 = int(d[1])
if x1 + x2 + x3 + x4 > y1 + y2 + y3 + y4:
    output_data = open('output.txt', 'w')
    output_data.write('1')
elif x1 + x2 + x3 + x4 < y1 + y2 + y3 + y4:
    output_data = open('output.txt', 'w')
    output_data.write('2')
else:
    output_data = open('output.txt', 'w')
    output_data.write('DRAW')